### ISSUE TITLE
Stop writing dirty python please

### ISSUE THREAD

**Issue by aswaathb** [mahudu97/eie4-rona-grade#1]
Your python ashames me.

`print("What was your grade (%) for year {}".format(i))`
`grade = float(input()) `

The input function take in a string as a prompt. The print statement is redundant; just feed the same prompt to the input function please. 

-Best
Your Hop Bartering mentor

**Comment by mahudu97** [comment]
https://github.com/mahudu97/eie4-rona-grade/pull/2 Fixes
